######################################################################
# Automatically generated by qmake (3.0) Thu Jan 1 10:45:09 2015
######################################################################

TEMPLATE = app
TARGET = generate_cpp_statemachine
INCLUDEPATH += .

QMAKE_CXXFLAGS += -std=c++0x

# Input
HEADERS += base_statemachine.h result_test_statemachine1.cpp
SOURCES += result_test_statemachine1.cpp test_statemachine1.cpp

