######################################################################
# Automatically generated by qmake (3.0) Thu Sep 10 10:04:02 2015
######################################################################

TEMPLATE = app
TARGET = pingpong
INCLUDEPATH += .

INCLUDEPATH += ../../generate_cpp_statemachine/

QMAKE_CXXFLAGS += -std=c++0x

# Input
SOURCES += \
    test_pingpong.cpp

HEADERS +=
